language: python
sudo: false
cache: pip
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
env:
  global:
    - TEST='-v --durations 25'
    - PYTHONFAULTHANDLER=x
    - PYTHONWARNINGS=all
install:
  - pip install -U pip tox flake8
  - pip install -r test-reqs.txt
script:
  - flake8
  - python -m pytest tests/
